# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf64e14a56525fbaaa0a2ec2ab95dbd2368a6ebabb973c782c61cd8beebdf92118179aeea2c4394873d382b8d09d27840e2e0627b0947934380be7c6d11fd24

test:
  secret_key_base: 8371fdb26428ff6b3b409d79c3e6259a4d4fa7d7a54a762bd1d463f67e8808ede73edafa12a49a4c7ff0b8eb0fba9bb28e2c9ea67da136e5dab1134a9ce29579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
